### ISSUE TITLE
Missing double click handler to open bond/atom dialogs

### ISSUE THREAD

**Issue by targos** [cheminfo/openchemlib-js#228] opened 2024-10-03 11:40 UTC
- Must be in fragment mode
- Tool: lasso
- Double click on atom or bond should open the corresponding dialog (same as pressing Q key)

**Comment by tpoisseau** [comment] 2024-10-07 08:11
Duplicate of https://github.com/cheminfo/openchemlib-js/issues/225

**Closed by tpoisseau** 2024-10-07 08:11 UTC
